/* 

This script purposes to bundle all the type declaration files into one bundle.
This needs to run after after d.ts files have been generated by the typescript compiler.

*/

const dts = require("dts-bundle");
const path = require("path");

const pkgJson = require("../package.json");

const contentDir = path.join(__dirname, "..");
console.log({ contentDir });

// react-loading-indicators/dist/mjs/indicators/Atom
const options = {
	name: pkgJson.name,
	main: `${contentDir}/dist/mjs/index.d.ts`,
	out: `${contentDir}/dist/index.d.ts`,
	// outputAsModuleFolder: false,
	baseDir: contentDir
	// prefix: `${pkgJson.name}/dist/mjs/indicators`
};

// run it
dts.bundle(options);
