/* 

This script purposes to bundle all the type declaration files into one bundle.
This needs to run after after d.ts files have been generated by the typescript compiler.

*/

const dts = require("dts-bundle");
const path = require("path");

const pkgJson = require("../package.json");

const distDir = path.join(__dirname, "../dist");
console.log({ distDir });

const options = {
	name: pkgJson.name,
	main: `${distDir}/types/index.d.ts`,
	out: `${distDir}/index.d.ts`
};

// run it
dts.bundle(options);
